export enum RootStack {
  Main = 'Main',
  My = 'My',
  Home = 'Home',
  Home2 = 'Home2',
  Certificate = 'Certificate',
  Page2 = 'Page2',
  IdentityVerification = 'IdentityVerification',
  Chatbot = 'Chatbot',
  InitialGuide = 'InitialGuide',
  TermsCheck = 'TermsCheck',
  UserCertificateCheck = 'UserCertificateCheck',
  UserCertificateGuide = 'UserCertificateGuide',
  UserCertificate = 'UserCertificate',
  PermissionGuide = 'PermissionGuide',
  NotificationSetting = 'NotificationSetting',
  ServiceTerms = 'ServiceTerms',
  PrivacyPolicy = 'PrivacyPolicy',
}
